flaskdb/flaskdb/views.py
"""
A Sample Web-DB Application for DB-DESIGN lecture
Copyright (C) 2022 Yasuhiro Hayashi
"""
from flask import Blueprint, request, session, render_template, redirect, flash, url_for
import datetime
import pickle

from flaskdb import apps, db, da
from flaskdb.models import User, Item,Task
from flaskdb.forms import LoginForm, AddItemForm, SearchItemForm,AddTaskForm,SearchCategoryForm

app = Blueprint("app", __name__)

@app.route("/", methods=["GET", "POST"])
def index():
    return render_template("/index.html")

@app.route("/now", methods=["GET", "POST"])
def now():
    return str(datetime.datetime.now())

# This is a very danger method
@app.route("/receive", methods=["GET", "POST"])
def receive():
    if request.method == "GET":
        username = request.args.get("username")
        password = request.args.get("password")
    else:
        username = request.form["username"]
        password = request.form["password"]

    return render_template("receive.html", username=username, password=password)

@app.route("/initdb", methods=["GET", "POST"])
def initdb():
    db.drop_all()
    db.create_all()#db作成
    
    admin = User(username="admin", password="password")
    user = User(username="user", password="password")
    db.session.add(admin)
    db.session.add(user)
    db.session.commit()
    return "initidb() method was executed. "

@app.route("/login", methods=["GET", "POST"])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        print(form.username.data)
        print(form.password.data)

        user = User.query.filter_by(username=form.username.data, password=form.password.data).first()

        if user is None or user.password != form.password.data:
            flash("Username or Password is incorrect.", "danger")
            return redirect(url_for("app.login"))

        session["username"] = user.username
        return redirect(url_for("app.index"))

    return render_template("login.html", form=form)

@app.route("/logout", methods=["GET", "POST"])
def logout():
    session.pop("username", None)
    session.clear()
    flash("You have been logged out.", "info")
    return redirect(url_for("app.index"))

@app.route("/additem", methods=["GET", "POST"])
def additem():
    if not "username" in session:
        flash("Log in is required.", "danger")
        return redirect(url_for("app.login"))

    form = AddItemForm()

    if form.validate_on_submit():
        item = Item()
        form.copy_to(item)
        user = User.query.filter_by(username=session["username"]).first()
        item.user_id = user.id
        db.session.add(item)
        db.session.commit()

        flash("An item was added.", "info")
        return redirect(url_for("app.additem"))

    itemlist = Item.query.all()
    return render_template("additem.html", form=form, itemlist=itemlist)

@app.route("/addtask", methods=["GET", "POST"])
def addtask():
    if not "username" in session:
        flash("Log in is required.", "danger")
        return redirect(url_for("app.login"))

    form = AddTaskForm()

    if form.validate_on_submit():
        task = Task()
        form.copy_to(task)
        #user = User.query.filter_by(username=session["username"]).first()
        db.session.add(task)
        db.session.commit()

        flash("An item was added.", "info")
        return redirect(url_for("app.addtask"))

    tasklist = Task.query.all()
    return render_template("addtask.html", form=form, tasklist=tasklist)#formでクラスを作成

@app.route("/searchitem", methods=["GET", "POST"])
def searchitem():
    if not "username" in session:
        flash("Log in is required.", "danger")
        return redirect(url_for("app.login"))

    form = SearchItemForm()

    if form.validate_on_submit():
        itemlist = Item.query.filter(Item.itemname.like("%" + form.itemname.data + "%")).all()        
        return render_template("search.html", form=form, itemlist=itemlist)

        # For change to PRG
        # itemlist = pickle.dumps(itemlist)
        # session["itemlist"] = itemlist
        # return redirect(url_for("app.searchitem"))

    # if "itemlist" in session:
    #     itemlist = session["itemlist"]
    #     itemlist = pickle.loads(itemlist)
    #     session.pop("itemlist", None)
    # else:
    #     itemlist = None
    # 
    # return render_template("search.html", form=form, itemlist=itemlist)

    return render_template("search.html", form=form)

@app.route("/search_category", methods=["GET", "POST"])#編集途中
def search_category():
    if not "username" in session:
        flash("Log in is required.", "danger")
        return redirect(url_for("app.login"))

    form = SearchCategoryForm()

    if form.validate_on_submit():
        itemlist = Task.query.filter(Task.category.like("%" + form.category.data + "%")).all()        
        return render_template("search_category.html", form=form, itemlist=itemlist)

    return render_template("search_category.html", form=form)

@app.route("/nativesql", methods=["GET", "POST"])
def nativesql():
    if not "username" in session:
        flash("Log in is required.", "danger")
        return redirect(url_for("app.login"))

    form = AddItemForm()

    if form.validate_on_submit():
        item = Item()
        form.copy_to(item)
        user = User.query.filter_by(username=session["username"]).first()
        item.user_id = user.id
        da.add_item(item)

        flash("An item was added.", "info")
        return redirect(url_for("app.additem"))

    itemlist = da.search_items()
    return render_template("additem.html", form=form, itemlist=itemlist)

@app.route("/nativesql2", methods=["GET", "POST"])
def nativesql2():
    if not "username" in session:
        flash("Log in is required.", "danger")
        return redirect(url_for("app.login"))

    form = AddTaskForm()

    if form.validate_on_submit():
        item = Task()
        form.copy_to(item)
        #user = User.query.filter_by(username=session["username"]).first()
        #item.user_id = user.id
        da.add_item(item)

        flash("An item was added.", "info")
        return redirect(url_for("app.addtask"))

    tasklist = da.search_items()
    return render_template("addtask.html", form=form, tasklist=tasklist)

flaskdb/flaskdb/templates/additem.html
{% extends "bootstrap/base.html" %}

{% block head %}
  <meta http-equiv="content-type" content="text/html; charset=UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>flaskdb | Add Item</title>
  <link href="//cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
  <link href="/static/css/flaskdb.css" rel="stylesheet">
  <!-- A Sample Web-DB Application for DB-DESIGN lecture -->
  <!-- Copyright (C) 2022 Yasuhiro Hayashi -->
{% endblock %}

{% block navbar %}
<div class="navbar navbar-inverse" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{{ url_for('app.index') }}">flaskdb</a>
    </div>
    <div class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        {% if not "username" in session %}
        <li><a href="{{ url_for('app.login') }}">Login</a></li>
        {% else %}
        <li><a href="{{ url_for('app.addtask') }}">Add Task</a></li>
        <li><a href="{{ url_for('app.additem') }}">Add Item</a></li>
        <li><a href="{{ url_for('app.searchitem') }}">Search Item</a></li>
        <li><a href="{{ url_for('app.search_category') }}">Search Category</a></li>
        <li><a href="{{ url_for('app.logout') }}">Logout</a></li>
        {% endif %}
      </ul>
    </div>
  </div>
</div>
{% endblock %}

{% block content %}
<div class="container">
  <div class="page-header"><h1>Add Item</h1></div>
  {% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
      {% for category, message in messages %}
        <div class="alert alert-{{ category }}"> {{ message|capitalize }} </div>
      {% endfor %}
    {% endif %}
  {% endwith %}
  {% if form %}
    {% for field in form.errors %}
      {% for error in form.errors[field] %}
        <div class="alert alert-danger">{{ error }}</div>
      {% endfor %}
    {% endfor %}
  {% endif %}
  <form action="{{ url_for('app.additem') }}" method="POST" novalidate class="mb-10">
    <div class="form-group">
      <label for="itemname">{{ form.itemname.label }}</label>
      {{ form.itemname(type="text", id="itemname", class="form-control", placeholder="Enter item name") }}
    </div>
    <div class="form-group">
      <label for="price">{{ form.price.label }}</label>
      {{ form.price(type="text", id="price", class="form-control", placeholder="Enter price") }}
    </div>
    {{ form.csrf_token }}
    {{ form.cancel(class="btn") }}
    {{ form.submit(class="btn btn-primary") }}
  </form>
  {% if itemlist %}
  <table class="table">
    <thead>
      <tr>
        <th scope="col">ID</th>
        <th scope="col">User ID</th>
        <th scope="col">Item Name</th>
        <th scope="col">Price</th>
      </tr>
    </thead>
    <tbody>
    {% for item in itemlist %}
        <tr>
          <th scope="row">{{ item.id }}</th>
          <td>{{ item.user_id }}</td>
          <td>{{ item.itemname }}</td>
          <td>{{ item.price }}</td>
        </tr>
    {% endfor %}
    </tbody>
  </table>
  {% endif %}
</div>
{% endblock %}

{% block scripts %}
<script src="{{ bootstrap_find_resource('jquery.js', cdn='jquery') }}"></script>
<script src="{{ bootstrap_find_resource('js/bootstrap.js', cdn='bootstrap') }}"></script>
<script src="/static/js/flaskdb.js"></script>
{% endblock %}

flaskdb/flaskdb/templates/addtask.html
{% extends "bootstrap/base.html" %}

{% block head %}
  <meta http-equiv="content-type" content="text/html; charset=UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>flaskdb | Add Task</title>
  <link href="//cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
  <link href="/static/css/flaskdb.css" rel="stylesheet">
  <!-- A Sample Web-DB Application for DB-DESIGN lecture -->
  <!-- Copyright (C) 2022 Yasuhiro Hayashi -->
{% endblock %}

{% block navbar %}
<div class="navbar navbar-inverse" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{{ url_for('app.index') }}">flaskdb</a>
    </div>
    <div class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        {% if not "username" in session %}
        <li><a href="{{ url_for('app.login') }}">Login</a></li>
        {% else %}
        <li><a href="{{ url_for('app.addtask') }}">Add Task</a></li>
        <li><a href="{{ url_for('app.additem') }}">Add Item</a></li>
        <li><a href="{{ url_for('app.searchitem') }}">Search Item</a></li>
        <li><a href="{{ url_for('app.search_category') }}">Search Category</a></li>
        <li><a href="{{ url_for('app.logout') }}">Logout</a></li>
        {% endif %}
      </ul>
    </div>
  </div>
</div>
{% endblock %}

{% block content %}
<div class="container">
  <div class="page-header"><h1>Add Task</h1></div>
  {% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
      {% for category, message in messages %}
        <div class="alert alert-{{ category }}"> {{ message|capitalize }} </div>
      {% endfor %}
    {% endif %}
  {% endwith %}
  {% if form %}
    {% for field in form.errors %}
      {% for error in form.errors[field] %}
        <div class="alert alert-danger">{{ error }}</div>
      {% endfor %}
    {% endfor %}
  {% endif %}
  <form action="{{ url_for('app.addtask') }}" method="POST" novalidate class="mb-10">
    <div class="form-group">
      <label for="category">{{ form.category.label }}</label>
      {{ form.category(type="text", id="category", class="form-control", placeholder="Enter category") }}
    </div>
    <div class="form-group">
      <label for="role">{{ form.role.label }}</label>
      {{ form.role(type="text", id="role", class="form-control", placeholder="Enter role") }}
    </div>
    <div class="form-group">
      <label for="task">{{ form.task.label }}</label>
      {{ form.task(type="text", id="task", class="form-control", placeholder="Enter task") }}
    </div>
    <div class="form-group">
      <label for="start_date">{{ form.start_date.label }}</label>
      {{ form.start_date(type="text", id="start_date", class="form-control", placeholder="Enter start_date") }}
    </div>
    <div class="form-group">
      <label for="final_date">{{ form.final_date.label }}</label>
      {{ form.final_date(type="text", id="final_date", class="form-control", placeholder="Enter final_date") }}
    </div>
    {{ form.csrf_token }}
    {{ form.cancel(class="btn") }}
    {{ form.submit(class="btn btn-primary") }}
  </form>
  {% if tasklist %}
  <table class="table">
    <thead>
      <tr>
        <th scope="col">ID</th>
        <th scope="col">category</th>
        <th scope="col">role</th>
        <th scope="col">Task</th>
        <th scope="col">Start_date</th>
        <th scope="col">Final_date</th>
      </tr>
    </thead>
    <tbody>
    {% for task in tasklist %}
        <tr>
          <th scope="row">{{ task.id }}</th>
          <td>{{ task.category }}</td>
          <td>{{ task.role }}</td>
          <td>{{ task.task }}</td>
          <td>{{ task.start_date }}</td>
          <td>{{ task.final_date }}</td>
        </tr>
    {% endfor %}
    </tbody>
  </table>
  {% endif %}
</div>
{% endblock %}

{% block scripts %}
<script src="{{ bootstrap_find_resource('jquery.js', cdn='jquery') }}"></script>
<script src="{{ bootstrap_find_resource('js/bootstrap.js', cdn='bootstrap') }}"></script>
<script src="/static/js/flaskdb.js"></script>
{% endblock %}

flaskdb/flaskdb/templates/index.html
{% extends "bootstrap/base.html" %}

{% block head %}
  <meta http-equiv="content-type" content="text/html; charset=UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>flaskdb | Index</title>
  <link href="//cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
  <link href="/static/css/flaskdb.css" rel="stylesheet">
  <!-- A Sample Web-DB Application for DB-DESIGN lecture -->
  <!-- Copyright (C) 2022 Yasuhiro Hayashi -->
{% endblock %}

{% block navbar %}
<div class="navbar navbar-inverse" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{{ url_for('app.index') }}">flaskdb</a>
    </div>
    <div class="navbar-collapse collapse"> 
      <ul class="nav navbar-nav">
        {% if not "username" in session %}
        <li><a href="{{ url_for('app.login') }}">Login</a></li>
        {% else %}
        <li><a href="{{ url_for('app.addtask') }}">Add Task</a></li>
        <li><a href="{{ url_for('app.additem') }}">Add Item</a></li>
        <li><a href="{{ url_for('app.searchitem') }}">Search Item</a></li>
        <li><a href="{{ url_for('app.search_category') }}">Search Category</a></li>
        <li><a href="{{ url_for('app.logout') }}">Logout</a></li>
        {% endif %}
      </ul>
    </div>
  </div>
</div>
{% endblock %}

{% block content %}
<div class="container">
  <div class="page-header"><h1>Index</h1></div>
  {% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
      {% for category, message in messages %}
        <div class="alert alert-{{ category }}"> {{ message|capitalize }} </div>
      {% endfor %}
    {% endif %}
  {% endwith %}
  {% if form %}
    {% for field in form.errors %}
      {% for error in form.errors[field] %}
        <div class="alert alert-danger">{{ error }}</div>
      {% endfor %}
    {% endfor %}
  {% endif %}
  {% if "username" in session %}
  <p>Welcome, {{ session["username"] }}!</p>
  {% endif %}
</div>
{% endblock %}

{% block scripts %}
<script src="{{ bootstrap_find_resource('jquery.js', cdn='jquery') }}"></script>
<script src="{{ bootstrap_find_resource('js/bootstrap.js', cdn='bootstrap') }}"></script>
<script src="/static/js/flaskdb.js"></script>
{% endblock %}

flaskdb/flaskdb/templates/nativesql.html
{% extends "bootstrap/base.html" %}

{% block head %}
  <meta http-equiv="content-type" content="text/html; charset=UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>flaskdb | Add Item</title>
  <link href="//cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
  <link href="/static/css/flaskdb.css" rel="stylesheet">
  <!-- A Sample Web-DB Application for DB-DESIGN lecture -->
  <!-- Copyright (C) 2022 Yasuhiro Hayashi -->
{% endblock %}

{% block navbar %}
<div class="navbar navbar-inverse" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{{ url_for('app.index') }}">flaskdb</a>
    </div>
    <div class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        {% if not "username" in session %}
        <li><a href="{{ url_for('app.login') }}">Login</a></li>
        {% else %}
        <li><a href="{{ url_for('app.additem') }}">Add Item</a></li>
        <li><a href="{{ url_for('app.searchitem') }}">Search Item</a></li>
        <li><a href="{{ url_for('app.logout') }}">Logout</a></li>
        {% endif %}
      </ul>
    </div>
  </div>
</div>
{% endblock %}

{% block content %}
<div class="container">
  <div class="page-header"><h1>Add Item</h1></div>
  {% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
      {% for category, message in messages %}
        <div class="alert alert-{{ category }}"> {{ message|capitalize }} </div>
      {% endfor %}
    {% endif %}
  {% endwith %}
  {% if form %}
    {% for field in form.errors %}
      {% for error in form.errors[field] %}
        <div class="alert alert-danger">{{ error }}</div>
      {% endfor %}
    {% endfor %}
  {% endif %}
  <form action="{{ url_for('app.nativesql') }}" method="POST" novalidate class="mb-10">
    <div class="form-group">
      <label for="itemname">{{ form.itemname.label }}</label>
      {{ form.itemname(type="text", id="itemname", class="form-control", placeholder="Enter item name") }}
    </div>
    <div class="form-group">
      <label for="price">{{ form.price.label }}</label>
      {{ form.price(type="text", id="price", class="form-control", placeholder="Enter price") }}
    </div>
    {{ form.csrf_token }}
    {{ form.cancel(class="btn") }}
    {{ form.submit(class="btn btn-primary") }}
  </form>
  {% if itemlist %}
  <table class="table">
    <thead>
      <tr>
        <th scope="col">ID</th>
        <th scope="col">User ID</th>
        <th scope="col">Item Name</th>
        <th scope="col">Price</th>
      </tr>
    </thead>
    <tbody>
    {% for item in itemlist %}
        <tr>
          <th scope="row">{{ item.id }}</th>
          <td>{{ item.user_id }}</td>
          <td>{{ item.itemname }}</td>
          <td>{{ item.price }}</td>
        </tr>
    {% endfor %}
    </tbody>
  </table>
  {% endif %}
</div>
{% endblock %}

{% block scripts %}
<script src="{{ bootstrap_find_resource('jquery.js', cdn='jquery') }}"></script>
<script src="{{ bootstrap_find_resource('js/bootstrap.js', cdn='bootstrap') }}"></script>
<script src="/static/js/flaskdb.js"></script>
{% endblock %}

flaskdb/flaskdb/templates/nativsql2.html
{% extends "bootstrap/base.html" %}

{% block head %}
  <meta http-equiv="content-type" content="text/html; charset=UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>flaskdb | Add Item</title>
  <link href="//cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
  <link href="/static/css/flaskdb.css" rel="stylesheet">
  <!-- A Sample Web-DB Application for DB-DESIGN lecture -->
  <!-- Copyright (C) 2022 Yasuhiro Hayashi -->
{% endblock %}

{% block navbar %}
<div class="navbar navbar-inverse" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{{ url_for('app.index') }}">flaskdb</a>
    </div>
    <div class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        {% if not "username" in session %}
        <li><a href="{{ url_for('app.login') }}">Login</a></li>
        {% else %}
        <li><a href="{{ url_for('app.addtask') }}">Add Task</a></li>
        li><a href="{{ url_for('app.additem') }}">Add Item</a></li>
        <li><a href="{{ url_for('app.searchitem') }}">Search Item</a></li>
        <li><a href="{{ url_for('app.logout') }}">Logout</a></li>
        {% endif %}
      </ul>
    </div>
  </div>
</div>
{% endblock %}

{% block content %}
<div class="container">
  <div class="page-header"><h1>Add Task</h1></div>
  {% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
      {% for category, message in messages %}
        <div class="alert alert-{{ category }}"> {{ message|capitalize }} </div>
      {% endfor %}
    {% endif %}
  {% endwith %}
  {% if form %}
    {% for field in form.errors %}
      {% for error in form.errors[field] %}
        <div class="alert alert-danger">{{ error }}</div>
      {% endfor %}
    {% endfor %}
  {% endif %}
  <form action="{{ url_for('app.nativesql2') }}" method="POST" novalidate class="mb-10">
    <div class="form-group">
        <label for="category">{{ form.category.label }}</label>
        {{ form.category(type="text", id="category", class="form-control", placeholder="Enter category") }}
    </div>
    <div class="form-group">
        <label for="task">{{ form.task.label }}</label>
        {{ form.task(type="text", id="task", class="form-control", placeholder="Enter task name") }}
    </div>
    <div class="form-group">
        <label for="role">{{ form.role.label }}</label>
        {{ form.role(type="text", id="role", class="form-control", placeholder="Enter role") }}
    </div>
    <div class="form-group">
        <label for="start_date">{{ form.start_date.label }}</label>
        {{ form.start_date(type="text", id="start_date", class="form-control", placeholder="Enter start_date") }}
    </div>
    <div class="form-group">
        <label for="final_date">{{ form.final_date.label }}</label>
        {{ form.role(type="text", id="final_date", class="form-control", placeholder="Enter final_date") }}
    </div>
    {{ form.csrf_token }}
    {{ form.cancel(class="btn") }}
    {{ form.submit(class="btn btn-primary") }}
  </form>
  {% if tasklist %}
  <table class="table">
    <thead>
      <tr>
        <th scope="col">ID</th>
        <th scope="col">Category</th>
        <th scope="col">Role</th>
        <th scope="col">Task</th>
        <th scope="col">Start_date</th>
        <th scope="col">Final_date</th>
      </tr>
    </thead>
    <tbody>
    {% for item in tasklist %}
        <tr>
          <th scope="row">{{ task.id }}</th>
          <td>{{ task.category }}</td>
          <td>{{ task.role }}</td>
          <td>{{ task.task }}</td>
          <td>{{ task.start_date }}</td>
          <td>{{ task.final_date }}</td>
        </tr>
    {% endfor %}
    </tbody>
  </table>
  {% endif %}
</div>
{% endblock %}

{% block scripts %}
<script src="{{ bootstrap_find_resource('jquery.js', cdn='jquery') }}"></script>
<script src="{{ bootstrap_find_resource('js/bootstrap.js', cdn='bootstrap') }}"></script>
<script src="/static/js/flaskdb.js"></script>
{% endblock %}

flaskdb/flaskdb/templates/receive.html
<!DOCTYPE html>
<html>
<head>
<title>flaskdb | receive</title>
<!-- A Sample Web-DB Application for DB-DESIGN lecture -->
<!-- Copyright (C) 2022 Yasuhiro Hayashi -->
</head>
<body>

<h2>GET:</h2>
<div><a href="{{ url_for('app.receive') }}">{{ url_for('app.receive') }}</a></div>
<div><a href="{{ url_for('app.receive') }}?username=taro&password=password">{{ url_for('app.receive') }}?username=taro&password=password</a></div>
<br>
<br>
<br>

<h2>POST:</h2>
<form action="{{ url_for('app.receive') }}" method="POST">
<input type="text" name="username" placeholder="Input your name">
<input type="password" name="password" placeholder="Input your password">
<button type="button">Cancel</button>
<input type="submit" value="Login">
</form>
<br>
<br>
<br>

<h2>Received Data:</h2>
<div>username: {{ username }}</div>
<div>password: {{ password }}</div>

</body>
</html>